<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Statistical Hypothesis Testing - The Classical Approach | WBS DBA: Introduction to Quantitative Analysis</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Statistical Hypothesis Testing - The Classical Approach | WBS DBA: Introduction to Quantitative Analysis" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Statistical Hypothesis Testing - The Classical Approach | WBS DBA: Introduction to Quantitative Analysis" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Yihui Xie" />


<meta name="date" content="2024-01-12" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="references.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">WBS DBA Quantitative Methods</li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction and Orientation</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Describing the World With Data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#box-plots"><i class="fa fa-check"></i><b>2.1</b> Box Plots</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#violin-plots"><i class="fa fa-check"></i><b>2.2</b> Violin Plots</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#describing-variables-and-distributions"><i class="fa fa-check"></i><b>2.3</b> Describing Variables and Distributions</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#transformations"><i class="fa fa-check"></i><b>2.4</b> Transformations</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="assoc_rel.html"><a href="assoc_rel.html"><i class="fa fa-check"></i><b>3</b> Associations and Relationships</a>
<ul>
<li class="chapter" data-level="3.1" data-path="assoc_rel.html"><a href="assoc_rel.html#correlations-and-associations"><i class="fa fa-check"></i><b>3.1</b> Correlations and Associations</a></li>
<li class="chapter" data-level="3.2" data-path="assoc_rel.html"><a href="assoc_rel.html#regression"><i class="fa fa-check"></i><b>3.2</b> Regression</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="assoc_rel.html"><a href="assoc_rel.html#figure-5.1-page-124-linear-regression-of-sons-on-fathers-heights"><i class="fa fa-check"></i><b>3.2.1</b> Figure 5.1 (page 124) Linear regression of sons’ on fathers’ heights</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="assoc_rel.html"><a href="assoc_rel.html#multiple-regression"><i class="fa fa-check"></i><b>3.3</b> Multiple Regression</a></li>
<li class="chapter" data-level="3.4" data-path="assoc_rel.html"><a href="assoc_rel.html#visualizing-multiple-regression"><i class="fa fa-check"></i><b>3.4</b> Visualizing Multiple Regression</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="methods.html"><a href="methods.html"><i class="fa fa-check"></i><b>4</b> Methods</a>
<ul>
<li class="chapter" data-level="4.1" data-path="methods.html"><a href="methods.html#math-example"><i class="fa fa-check"></i><b>4.1</b> math example</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="applications.html"><a href="applications.html"><i class="fa fa-check"></i><b>5</b> Applications</a>
<ul>
<li class="chapter" data-level="5.1" data-path="applications.html"><a href="applications.html#example-one"><i class="fa fa-check"></i><b>5.1</b> Example one</a></li>
<li class="chapter" data-level="5.2" data-path="applications.html"><a href="applications.html#example-two"><i class="fa fa-check"></i><b>5.2</b> Example two</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="final-words.html"><a href="final-words.html"><i class="fa fa-check"></i><b>6</b> Final Words</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="7" data-path="statistical-hypothesis-testing---the-classical-approach.html"><a href="statistical-hypothesis-testing---the-classical-approach.html"><i class="fa fa-check"></i><b>7</b> Statistical Hypothesis Testing - The Classical Approach</a>
<ul>
<li class="chapter" data-level="7.1" data-path="statistical-hypothesis-testing---the-classical-approach.html"><a href="statistical-hypothesis-testing---the-classical-approach.html#premier-league-goals-and-the-poisson-distribution"><i class="fa fa-check"></i><b>7.1</b> Premier League Goals and the Poisson Distribution</a></li>
<li class="chapter" data-level="7.2" data-path="statistical-hypothesis-testing---the-classical-approach.html"><a href="statistical-hypothesis-testing---the-classical-approach.html#correlation-significance-tests"><i class="fa fa-check"></i><b>7.2</b> Correlation Significance Tests</a></li>
<li class="chapter" data-level="7.3" data-path="statistical-hypothesis-testing---the-classical-approach.html"><a href="statistical-hypothesis-testing---the-classical-approach.html#regression-significance-tests"><i class="fa fa-check"></i><b>7.3</b> Regression Significance Tests</a></li>
<li class="chapter" data-level="7.4" data-path="statistical-hypothesis-testing---the-classical-approach.html"><a href="statistical-hypothesis-testing---the-classical-approach.html#anova"><i class="fa fa-check"></i><b>7.4</b> ANOVA</a></li>
<li class="chapter" data-level="7.5" data-path="statistical-hypothesis-testing---the-classical-approach.html"><a href="statistical-hypothesis-testing---the-classical-approach.html#rate-of-change-in-football-goals-per-season---bonferroni-correction"><i class="fa fa-check"></i><b>7.5</b> Rate of Change in Football Goals per Season - Bonferroni Correction?</a></li>
<li class="chapter" data-level="7.6" data-path="statistical-hypothesis-testing---the-classical-approach.html"><a href="statistical-hypothesis-testing---the-classical-approach.html#statistical-power"><i class="fa fa-check"></i><b>7.6</b> Statistical Power</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">WBS DBA: Introduction to Quantitative Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistical-hypothesis-testing---the-classical-approach" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> Statistical Hypothesis Testing - The Classical Approach<a href="statistical-hypothesis-testing---the-classical-approach.html#statistical-hypothesis-testing---the-classical-approach" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This lesson contains some (re)worked examples from earlier sessions, focusing specifically on the hypothesis testing aspect of them.</p>
<div id="premier-league-goals-and-the-poisson-distribution" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Premier League Goals and the Poisson Distribution<a href="statistical-hypothesis-testing---the-classical-approach.html#premier-league-goals-and-the-poisson-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section, we are not really worried about the <em>actual</em> goals or anything like that. What we are concerned about is formally testing the hypothesis that Premier League goals per game actually do follow a Poisson distribution. To do this, we will use what is called a <strong>chi-square</strong> test, which uses the chi-square statistic.</p>
<p>Chi-square is a fantastically versatile statistic, which is often used to compare tables of observations. Commonly, we compare a table of observed events with a table of events that we would expect if the null hypothesis were true in the population. The chi-square value is the measure of the difference between observed and expected counts in the table. We can use it here to compare the amount of goals we actually did observe in the 21-22 season, with those that we would <em>expect</em> to observe if the goals per game really do follow a Poisson distribution.</p>
<p>Again, much of the idea and code for this section comes from: <a href="https://bookdown.org/theqdata/honors_thesis/goal-scoring-and-the-poisson-process.html" class="uri">https://bookdown.org/theqdata/honors_thesis/goal-scoring-and-the-poisson-process.html</a></p>
<p>The data comes from: <a href="https://www.football-data.co.uk/englandm.php" class="uri">https://www.football-data.co.uk/englandm.php</a> and is the EPL results for 21-22 Season, with a new column of Total Goals (TOTG) created by me in Excel.</p>
<pre><code>## # A tibble: 6 × 107
##   Div   Date                Time                HomeTeam   AwayTeam   FTHG  FTAG
##   &lt;chr&gt; &lt;dttm&gt;              &lt;dttm&gt;              &lt;chr&gt;      &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1 E0    2021-08-13 00:00:00 1899-12-31 20:00:00 Brentford  Arsenal       2     0
## 2 E0    2021-08-14 00:00:00 1899-12-31 12:30:00 Man United Leeds         5     1
## 3 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Burnley    Brighton      1     2
## 4 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Chelsea    Crystal …     3     0
## 5 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Everton    Southamp…     3     1
## 6 E0    2021-08-14 00:00:00 1899-12-31 15:00:00 Leicester  Wolves        1     0
## # ℹ 100 more variables: TOTG &lt;dbl&gt;, FTR &lt;chr&gt;, HTHG &lt;dbl&gt;, HTAG &lt;dbl&gt;,
## #   HTR &lt;chr&gt;, Referee &lt;chr&gt;, HS &lt;dbl&gt;, AS &lt;dbl&gt;, HST &lt;dbl&gt;, AST &lt;dbl&gt;,
## #   HF &lt;dbl&gt;, AF &lt;dbl&gt;, HC &lt;dbl&gt;, AC &lt;dbl&gt;, HY &lt;dbl&gt;, AY &lt;dbl&gt;, HR &lt;dbl&gt;,
## #   AR &lt;dbl&gt;, B365H &lt;dbl&gt;, B365D &lt;dbl&gt;, B365A &lt;dbl&gt;, BWH &lt;dbl&gt;, BWD &lt;dbl&gt;,
## #   BWA &lt;dbl&gt;, IWH &lt;dbl&gt;, IWD &lt;dbl&gt;, IWA &lt;dbl&gt;, PSH &lt;dbl&gt;, PSD &lt;dbl&gt;,
## #   PSA &lt;dbl&gt;, WHH &lt;dbl&gt;, WHD &lt;dbl&gt;, WHA &lt;dbl&gt;, VCH &lt;dbl&gt;, VCD &lt;dbl&gt;,
## #   VCA &lt;dbl&gt;, MaxH &lt;dbl&gt;, MaxD &lt;dbl&gt;, MaxA &lt;dbl&gt;, AvgH &lt;dbl&gt;, AvgD &lt;dbl&gt;, …</code></pre>
<pre><code>##    Length     Class      Mode 
##       380 character character</code></pre>
<p>The above is a quick way of calculating / checking the total number of games if you don’t know already.</p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   2.000   3.000   2.818   4.000   9.000</code></pre>
<pre><code>## [1] 1071</code></pre>
<p>First, let’s create a table of all the matches with different numbers of goals, just as we did in Lesson 6.</p>
<pre><code>## # A tibble: 9 × 2
##    TOTG ActualMatches
##   &lt;dbl&gt;         &lt;int&gt;
## 1     0            22
## 2     1            65
## 3     2            88
## 4     3            81
## 5     4            60
## 6     5            43
## 7     6            17
## 8     7             3
## 9     9             1</code></pre>
<p>Here, we have a problem. The chi-square test has a condition that the expected values in every column will be greater than 5, and as we go down the Poisson probabilities (i.e. for higher total goals), it is clear that this will start to become a problem for us.</p>
<p>The solution is simple, we combine the numbers for larger numbers of goals into a single ‘x and above’ variable. Here, let’s do it for 6 goals and above.</p>
<p>To do so, we first need to create a new table, where the values for 6 and above are combined into a new row.</p>
<pre><code>## # A tibble: 7 × 2
##   TOTG      ActualMatches
##   &lt;chr&gt;             &lt;int&gt;
## 1 0                    22
## 2 1                    65
## 3 2                    88
## 4 3                    81
## 5 4                    60
## 6 5                    43
## 7 6 or more            21</code></pre>
<p>Now we can create the Poisson distribution for the relevant mean, which means we first need to create the stats…</p>
<pre><code>##  min Q1 median Q3 max     mean       sd   n missing
##    0  2      3  4   9 2.818421 1.626359 380       0</code></pre>
<p>Below is some code which will help us to create the distributions and also check them.</p>
<pre><code>## [1] 2.818421</code></pre>
<pre><code>## [1] 2.645042</code></pre>
<p>As we saw in Lesson 7, while for a Poisson distribution these should be exactly the same, we decided that they were good enough to be going on with.</p>
<p>So, let’s actually check this formally with the Chi-square test.</p>
<p>We do so by first creating a table of the Poisson probabilities for x or fewer goals, for the Poisson with a mean of 2.818 (i.e. the variable MeanGoals)</p>
<pre><code>##     PoisProb
## 1 0.05970013
## 2 0.16826011
## 3 0.23711392
## 4 0.22276228
## 5 0.15695948
## 6 0.08847558
## 7 0.04156024</code></pre>
<p>This allows us to make some predictions of what we could expect.</p>
<p>Remembering again that there are 380 games in a season, we can see that there is a 0.16% chance of seeing 4 goals in a game, which equates to 380 x 0.16 = 60.8 games we would expect to see in a season with 4 goals.</p>
<p>We can check this out by creating a new table comparing actual with predicted values…</p>
<pre><code>##        TOTG ActualMatches   PoisProb ExpectedMatches
## 1         0            22 0.05970013              23
## 2         1            65 0.16826011              64
## 3         2            88 0.23711392              90
## 4         3            81 0.22276228              85
## 5         4            60 0.15695948              60
## 6         5            43 0.08847558              34
## 7 6 or more            21 0.04156024              16</code></pre>
<p>This looks quite frighteningly close up until you get to the 5 row. It will be interesting to see how we go with a formal chi-square test.</p>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  NewGoalsTable$ActualMatches
## X-squared = 4.2244, df = 6, p-value = 0.6463</code></pre>
<p>The P-value here is actually 0.64. This suggests that there is not a significant difference between the distribution of the actual goals, and that which would be expected if they did follow a Poisson distribution.</p>
</div>
<div id="correlation-significance-tests" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Correlation Significance Tests<a href="statistical-hypothesis-testing---the-classical-approach.html#correlation-significance-tests" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here, we revisit our correlation between GDP per capita, and Happiness metrics, which I pulled from Our Word in Data:</p>
<pre><code>##    Country            Happiness         GDPpc             Pop           
##  Length:249         Min.   :2.400   Min.   :   731   Min.   :8.090e+02  
##  Class :character   1st Qu.:4.670   1st Qu.:  4917   1st Qu.:4.153e+05  
##  Mode  :character   Median :5.530   Median : 12655   Median :5.596e+06  
##                     Mean   :5.492   Mean   : 20464   Mean   :5.918e+07  
##                     3rd Qu.:6.260   3rd Qu.: 30100   3rd Qu.:2.421e+07  
##                     Max.   :7.820   Max.   :112557   Max.   :4.663e+09  
##                     NA&#39;s   :96      NA&#39;s   :52       NA&#39;s   :7</code></pre>
<pre><code>## # A tibble: 6 × 4
##   Country        Happiness GDPpc      Pop
##   &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;
## 1 Afghanistan         2.4   1971 38972236
## 2 Albania             5.2  13192  2866850
## 3 Algeria             5.12 10735 43451668
## 4 American Samoa     NA       NA    46216
## 5 Andorra            NA       NA    77723
## 6 Angola             NA     6110 33428490</code></pre>
<p>Let’s not worry about plotting the data, and go straight to the correlation:</p>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  x and y
## t = 13.502, df = 146, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6636288 0.8092331
## sample estimates:
##      cor 
## 0.745184</code></pre>
<p>Here are our results. The estimate is a correlation, and we test that using the t statistic. The t-value is simply the estimate divided by the standard error (which we can’t see in this output), and is interpreted essentially as ‘how far from 0 is the estimate, in standard errors’.</p>
<p>The p-value for t is very very small, and obviously less than 0.05.</p>
</div>
<div id="regression-significance-tests" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Regression Significance Tests<a href="statistical-hypothesis-testing---the-classical-approach.html#regression-significance-tests" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The process to asses the significance of regression estimates is very very similar to that for correlations. Let’s revisit the heart disease data from: <a href="https://www.scribbr.com/statistics/linear-regression-in-r/" class="uri">https://www.scribbr.com/statistics/linear-regression-in-r/</a></p>
<pre><code>##       ...1           biking          smoking        heart.disease    
##  Min.   :  1.0   Min.   : 1.119   Min.   : 0.5259   Min.   : 0.5519  
##  1st Qu.:125.2   1st Qu.:20.205   1st Qu.: 8.2798   1st Qu.: 6.5137  
##  Median :249.5   Median :35.824   Median :15.8146   Median :10.3853  
##  Mean   :249.5   Mean   :37.788   Mean   :15.4350   Mean   :10.1745  
##  3rd Qu.:373.8   3rd Qu.:57.853   3rd Qu.:22.5689   3rd Qu.:13.7240  
##  Max.   :498.0   Max.   :74.907   Max.   :29.9467   Max.   :20.4535</code></pre>
<pre><code>## # A tibble: 6 × 4
##    ...1 biking smoking heart.disease
##   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;         &lt;dbl&gt;
## 1     1  30.8    10.9          11.8 
## 2     2  65.1     2.22          2.85
## 3     3   1.96   17.6          17.2 
## 4     4  44.8     2.80          6.82
## 5     5  69.4    16.0           4.06
## 6     6  54.4    29.3           9.55</code></pre>
<p>Let’s go straight the the multiple regression model.</p>
<pre><code>## 
## Call:
## lm(formula = heart.disease ~ biking + smoking, data = Heart)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.1789 -0.4463  0.0362  0.4422  1.9331 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 14.984658   0.080137  186.99   &lt;2e-16 ***
## biking      -0.200133   0.001366 -146.53   &lt;2e-16 ***
## smoking      0.178334   0.003539   50.39   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.654 on 495 degrees of freedom
## Multiple R-squared:  0.9796, Adjusted R-squared:  0.9795 
## F-statistic: 1.19e+04 on 2 and 495 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>We interpret these just as we did the correlation significance tests.</p>
<p>The t-value is large, and the p-value (two-tailed) is small.</p>
<p>Interestingly, R gives ‘stars’ for the different levels of significance, so to some extent they are doing some decision making for you.</p>
</div>
<div id="anova" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> ANOVA<a href="statistical-hypothesis-testing---the-classical-approach.html#anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here, I’ll demonstrate the basic application of ANOVA on the simple 3-group case of the Ed Sheeran Study:</p>
<pre><code>## # A tibble: 6 × 3
##      ID GROUP ANGER
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     1     1     2
## 2     2     2     5
## 3     3     1     2
## 4     4     3     3
## 5     5     2     4
## 6     6     3     2</code></pre>
<p>We need to tell R that GROUP is a factor variable not a numeric one:</p>
<p>Check it worked:</p>
<table>
<caption><span id="tab:unnamed-chunk-81">Table 7.1: </span>Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">ED</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">45</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">3</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">factor</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">2</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table>
<colgroup>
<col width="18%" />
<col width="13%" />
<col width="18%" />
<col width="10%" />
<col width="12%" />
<col width="26%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="left">ordered</th>
<th align="right">n_unique</th>
<th align="left">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">GROUP</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="left">FALSE</td>
<td align="right">3</td>
<td align="left">1: 15, 2: 15, 3: 15</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="18%" />
<col width="13%" />
<col width="18%" />
<col width="7%" />
<col width="7%" />
<col width="3%" />
<col width="5%" />
<col width="5%" />
<col width="5%" />
<col width="6%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ID</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">23.00</td>
<td align="right">13.13</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">23</td>
<td align="right">34</td>
<td align="right">45</td>
<td align="left">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td align="left">ANGER</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">3.22</td>
<td align="right">1.17</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">3</td>
<td align="right">4</td>
<td align="right">5</td>
<td align="left">▁▇▇▆▅</td>
</tr>
</tbody>
</table>
<p>Let’s create a quick table of the group means</p>
<pre><code>## # A tibble: 3 × 5
##   GROUP variable     n  mean    sd
##   &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 1     ANGER       15  2.33 0.816
## 2 2     ANGER       15  4.27 0.704
## 3 3     ANGER       15  3.07 1.03</code></pre>
<p>And now visualize that in a boxplot:</p>
<p><img src="DBA_files/figure-html/unnamed-chunk-83-1.png" width="672" /></p>
<p>Hmmm….</p>
<p>Let’s run an ANOVA (we’re using the rstatix package here not Base R)</p>
<p>Much of the following is drawn from: <a href="https://www.datanovia.com/en/lessons/anova-in-r/" class="uri">https://www.datanovia.com/en/lessons/anova-in-r/</a></p>
<pre><code>## ANOVA Table (type II tests)
## 
##   Effect DFn DFd      F        p p&lt;.05   ges
## 1  GROUP   2  42 19.235 1.17e-06     * 0.478</code></pre>
<p>Results here suggest there is a significant effect (p-value is very small) rstatix also gives us an ‘effect size’ measure (ges, generalized eta-squared) which is also useful to us and suggests the effect is quite large. This can be interpreted similarly to a regression coefficient (which is also an effect size measure), and is the amount of variance in the dependent variable (Anger) that is explained by group membership.</p>
<p>However, ANOVA only tests the ‘general effect’ of the treatment / group. We don’t know whether this is because of the difference between all of the groups, or only some. E.g., is it that there is an effect of music in general (i.e. between Control and Ed, and Control and Music, but not between Ed and Music), or that Ed specifically is anger-inducing (in whcih case we would see an effect between Ed and Music, and Ed and Control, and not between Music and Control).</p>
<p>We can investigate this using Post-Hoc tests, which compare the individual groups. This has the potential for a multiple comparisons problem, which we will need to deal with.</p>
<p>Let’s take a look back to the slide deck…</p>
<pre><code>## # A tibble: 3 × 9
##   term  group1 group2 null.value estimate conf.low conf.high       p.adj
## * &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;       &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 GROUP 1      2               0    1.93    1.17       2.70  0.000000734
## 2 GROUP 1      3               0    0.733  -0.0313     1.50  0.0625     
## 3 GROUP 2      3               0   -1.2    -1.96      -0.435 0.00126    
## # ℹ 1 more variable: p.adj.signif &lt;chr&gt;</code></pre>
<p>We can actually plot these results in a really effective way:</p>
<p><img src="DBA_files/figure-html/unnamed-chunk-86-1.png" width="672" /></p>
<p>This very clearly tells us that it is the Ed Sheeran group (2)that is driving these results, and there isn’t much to choose between the control group, and the ‘music’ group.</p>
<p>Now, there are many other things that if we were doing ANOVA that we would also look to deal with - such as the various assumptions required of ANOVA, and so forth. But, they are beyond our scope in this class. Suffice to say that this has only scratched the surface of ANOVA so far.</p>
</div>
<div id="rate-of-change-in-football-goals-per-season---bonferroni-correction" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Rate of Change in Football Goals per Season - Bonferroni Correction?<a href="statistical-hypothesis-testing---the-classical-approach.html#rate-of-change-in-football-goals-per-season---bonferroni-correction" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here, I’m using data from <a href="https://www.footballhistory.org/league/premier-league-statistics.html" class="uri">https://www.footballhistory.org/league/premier-league-statistics.html</a></p>
<p>I hand-entered this into a spreadsheet, and calculated the additional stuff.</p>
<pre><code>## # A tibble: 6 × 7
##   Season  Games Goals   GPG    SE Lower95CI Upper95CI
##   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 1995-96   380   988  2.6   31.4      926.     1050.
## 2 1996-97   380   970  2.55  31.1      909.     1031.
## 3 1997-98   380  1019  2.68  31.9      956.     1082.
## 4 1998-99   380   959  2.52  31.0      898.     1020.
## 5 1999-00   380  1060  2.79  32.6      996.     1124.
## 6 2000-01   380   992  2.61  31.5      930.     1054.</code></pre>
<p>You can see here I have calculated the standard errors from the yearly goal totals (which represent that year’s underlying rate of goal occurrence), then used that to calculate the 95% Confidence Interval limits</p>
<p>We can use these to create a nifty chart with the error bars…drawing from the code used by Spiegelhalter in his book for Figure 9.4 available on his github (linked in the code).</p>
<p><img src="DBA_files/figure-html/unnamed-chunk-88-1.png" width="672" /></p>
<p>From this chart, and looking at the data itself, we can see that the 95% Intervals overlap, so it is hard to conclude that the underlying rate of goals has changed significantly year on year. Yes, even in the pandemic.</p>
<p>Remember though, the ONS suggest that it is over-stringent to rely on error bar overlap, so we can also use z-tests to directly test the assumption that the change is zero.</p>
<p>See: <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/compendium/focusonviolentcrimeandsexualoffences/yearendingmarch2016/homicide#statistical-interpretation-of-trends-in-homicides" class="uri">https://www.ons.gov.uk/peoplepopulationandcommunity/crimeandjustice/compendium/focusonviolentcrimeandsexualoffences/yearendingmarch2016/homicide#statistical-interpretation-of-trends-in-homicides</a></p>
<p>Rather than just use a z-value cutoff of 1.96 as we did last time, in the next data file, I have calculated the p-value (2 tailed as we do not hypothesize a direction for the difference) for the z-scores for the difference between each season, year-on-year.</p>
<pre><code>## # A tibble: 6 × 11
##   Season  Games Goals   GPG    SE Lower95CI Upper95CI Change      Z negged
##   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 1995-96   380   988  2.6   31.4      926.     1050.     NA NA     NA    
## 2 1996-97   380   970  2.55  31.1      909.     1031.    -18 -0.407 -0.407
## 3 1997-98   380  1019  2.68  31.9      956.     1082.     49  1.10  -1.10 
## 4 1998-99   380   959  2.52  31.0      898.     1020.    -60 -1.35  -1.35 
## 5 1999-00   380  1060  2.79  32.6      996.     1124.    101  2.25  -2.25 
## 6 2000-01   380   992  2.61  31.5      930.     1054.    -68 -1.50  -1.50 
## # ℹ 1 more variable: p2 &lt;dbl&gt;</code></pre>
<p>Here, we can plot the p-values (2-tailed), and again we see (just like with the z-tests) that the same two seasons have significant differences.</p>
<p><img src="DBA_files/figure-html/unnamed-chunk-90-1.png" width="672" /></p>
<p>We can see that the 1999-2000 season, and the 2009-10 seasons have p values less than 0.05</p>
<p>The question is are we suffering from the multiple comparisons problem? Should we correct for it? It’s hard to say actually. Of course, we are indeed running multiple tests, 29 in fact. So, the chance of a false positive is quite high, if the null was true in all cases. The Bonferroni correction would immediately reduce this, but at the cost of making none of our tests significant.</p>
<p>Further, the basis of these corrections is that the null hypothesis is true. What if it is the alternative hypothesis (that is, the H of an effect existing) that is true? In such cases, there can of course be no false positives. Here, you are increasing the chances of a false negative by reducing the chances of a false positive. So, what are the potential costs of each of these mistakes?</p>
<p>For example, Thomas Perneger’s 1998 paper in the BMJ is scathing about the Bonferroni adjustment. Take a look at <a href="https://www.bmj.com/content/316/7139/1236.full" class="uri">https://www.bmj.com/content/316/7139/1236.full</a></p>
<p>Mind you, I am not saying that’s the final word, just that there are multiple perspectives on the issues!</p>
<p>It’s never as simple as it seems when making statistical decisions, is it?</p>
</div>
<div id="statistical-power" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> Statistical Power<a href="statistical-hypothesis-testing---the-classical-approach.html#statistical-power" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Different types of analysis and research design require different types of power calculation. In R, we can use the pwr package to calculate quite a few.</p>
<p>Let’s calculate the required sample size for the Ed Sheeran study we conducted earlier. Really, we should have done this before collecting data, but it’s a nice example to do it post hoc.</p>
<p>We don’t need the data, just the parameters of the experiment and analysis design.</p>
<p>So, we had 3 groups, and used ANOVA</p>
<p>Let’s set a significance of 0.05, a required power of 0.8, and assume the effect size is moderate (say 0.25)</p>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##               k = 3
##               n = 52.3966
##               f = 0.25
##       sig.level = 0.05
##           power = 0.8
## 
## NOTE: n is number in each group</code></pre>
<p>So, we really wanted to have around 50 in each group to have an 80% chance of detecting a moderate effect presuming the null was true.</p>
<p>You can see that my study (with only 15 in each group) was rather underpowered. However, if I had increased the effect size in the calculation to 0.5 (close to what the experiment suggested) this would have given me a result for n closer to what I actually used. However, you’d have to be VERY confident in the size of your likely effect to actually do that I think.</p>

</div>
</div>










            </section>

          </div>
        </div>
      </div>
<a href="references.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/07_H-Testing.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["DBA.pdf", "DBA.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
